clear all;
close all;
clc;

%Flow and Magnetic parameters
Ro_p=1050; r=5/10^6; V_p=(4/3)*pi*r^3; Ro_f=1000; m_p=Ro_p*V_p; m_f=(4/3)*pi*r^3*Ro_f; g=9.81;
mu_0=4*pi*10^(-7); ki_p=-8.2*10^(-6); ki_f=7.485*10^(-6); mu_f=8.9/10^4; nu_f=mu_f/Ro_f;

mu0=(4*pi)/10^7;

% Magnet properties
xb=0.0254/2;
yb=0.00635/2;
zb=0.00635/2;
M0=1.4/mu0;

syms x y z

Bx=((mu0*M0)/(4*pi))*(-log(y+yb-yb+((x+xb-xb)^2+(y+yb-yb)^2+(z-zb)^2)^0.5)...
           +log(y+yb-yb+((x+xb+xb)^2+(y+yb-yb)^2+(z-zb)^2)^0.5)...
           +log(y+yb+yb+((x+xb-xb)^2+(y+yb+yb)^2+(z-zb)^2)^0.5)...
           -log(y+yb+yb+((x+xb+xb)^2+(y+yb+yb)^2+(z-zb)^2)^0.5)...
           +log(y+yb-yb+((x+xb-xb)^2+(y+yb-yb)^2+(z+zb)^2)^0.5)...
           -log(y+yb-yb+((x+xb+xb)^2+(y+yb-yb)^2+(z+zb)^2)^0.5)...
           -log(y+yb+yb+((x+xb-xb)^2+(y+yb+yb)^2+(z+zb)^2)^0.5)...
           +log(y+yb+yb+((x+xb+xb)^2+(y+yb+yb)^2+(z+zb)^2)^0.5))...
           -((mu0*M0)/(4*pi))*(-log(y-yb-yb+((x+xb-xb)^2+(y-yb-yb)^2+(z-zb)^2)^0.5)...
           +log(y-yb-yb+((x+xb+xb)^2+(y-yb-yb)^2+(z-zb)^2)^0.5)...
           +log(y-yb+yb+((x+xb-xb)^2+(y-yb+yb)^2+(z-zb)^2)^0.5)...
           -log(y-yb+yb+((x+xb+xb)^2+(y-yb+yb)^2+(z-zb)^2)^0.5)...
           +log(y-yb-yb+((x+xb-xb)^2+(y-yb-yb)^2+(z+zb)^2)^0.5)...
           -log(y-yb-yb+((x+xb+xb)^2+(y-yb-yb)^2+(z+zb)^2)^0.5)...
           -log(y-yb+yb+((x+xb-xb)^2+(y-yb+yb)^2+(z+zb)^2)^0.5)...
           +log(y-yb+yb+((x+xb+xb)^2+(y-yb+yb)^2+(z+zb)^2)^0.5))...
           +((mu0*M0)/(4*pi))*(-log(y-yb-yb+((x-xb-xb)^2+(y-yb-yb)^2+(z-zb)^2)^0.5)...
           +log(y-yb-yb+((x-xb+xb)^2+(y-yb-yb)^2+(z-zb)^2)^0.5)...
           +log(y-yb+yb+((x-xb-xb)^2+(y-yb+yb)^2+(z-zb)^2)^0.5)...
           -log(y-yb+yb+((x-xb+xb)^2+(y-yb+yb)^2+(z-zb)^2)^0.5)...
           +log(y-yb-yb+((x-xb-xb)^2+(y-yb-yb)^2+(z+zb)^2)^0.5)...
           -log(y-yb-yb+((x-xb+xb)^2+(y-yb-yb)^2+(z+zb)^2)^0.5)...
           -log(y-yb+yb+((x-xb-xb)^2+(y-yb+yb)^2+(z+zb)^2)^0.5)...
           +log(y-yb+yb+((x-xb+xb)^2+(y-yb+yb)^2+(z+zb)^2)^0.5))...
           -((mu0*M0)/(4*pi))*(-log(y+yb-yb+((x-xb-xb)^2+(y+yb-yb)^2+(z-zb)^2)^0.5)...
           +log(y+yb-yb+((x-xb+xb)^2+(y+yb-yb)^2+(z-zb)^2)^0.5)...
           +log(y+yb+yb+((x-xb-xb)^2+(y+yb+yb)^2+(z-zb)^2)^0.5)...
           -log(y+yb+yb+((x-xb+xb)^2+(y+yb+yb)^2+(z-zb)^2)^0.5)...
           +log(y+yb-yb+((x-xb-xb)^2+(y+yb-yb)^2+(z+zb)^2)^0.5)...
           -log(y+yb-yb+((x-xb+xb)^2+(y+yb-yb)^2+(z+zb)^2)^0.5)...
           -log(y+yb+yb+((x-xb-xb)^2+(y+yb+yb)^2+(z+zb)^2)^0.5)...
           +log(y+yb+yb+((x-xb+xb)^2+(y+yb+yb)^2+(z+zb)^2)^0.5));
       
       By=((mu0*M0)/(4*pi))*(-log(x+xb-xb+((x+xb-xb)^2+(y+yb-yb)^2+(z-zb)^2)^0.5)...
           +log(x+xb+xb+((x+xb+xb)^2+(y+yb-yb)^2+(z-zb)^2)^0.5)...
           +log(x+xb-xb+((x+xb-xb)^2+(y+yb+yb)^2+(z-zb)^2)^0.5)...
           -log(x+xb+xb+((x+xb+xb)^2+(y+yb+yb)^2+(z-zb)^2)^0.5)...
           +log(x+xb-xb+((x+xb-xb)^2+(y+yb-yb)^2+(z+zb)^2)^0.5)...
           -log(x+xb+xb+((x+xb+xb)^2+(y+yb-yb)^2+(z+zb)^2)^0.5)...
           -log(x+xb-xb+((x+xb-xb)^2+(y+yb+yb)^2+(z+zb)^2)^0.5)...
           +log(x+xb+xb+((x+xb+xb)^2+(y+yb+yb)^2+(z+zb)^2)^0.5))...
           -((mu0*M0)/(4*pi))*(-log(x+xb-xb+((x+xb-xb)^2+(y-yb-yb)^2+(z-zb)^2)^0.5)...
           +log(x+xb+xb+((x+xb+xb)^2+(y-yb-yb)^2+(z-zb)^2)^0.5)...
           +log(x+xb-xb+((x+xb-xb)^2+(y-yb+yb)^2+(z-zb)^2)^0.5)...
           -log(x+xb+xb+((x+xb+xb)^2+(y-yb+yb)^2+(z-zb)^2)^0.5)...
           +log(x+xb-xb+((x+xb-xb)^2+(y-yb-yb)^2+(z+zb)^2)^0.5)...
           -log(x+xb+xb+((x+xb+xb)^2+(y-yb-yb)^2+(z+zb)^2)^0.5)...
           -log(x+xb-xb+((x+xb-xb)^2+(y-yb+yb)^2+(z+zb)^2)^0.5)...
           +log(x+xb+xb+((x+xb+xb)^2+(y-yb+yb)^2+(z+zb)^2)^0.5))...
           +((mu0*M0)/(4*pi))*(-log(x-xb-xb+((x-xb-xb)^2+(y-yb-yb)^2+(z-zb)^2)^0.5)...
           +log(x-xb+xb+((x-xb+xb)^2+(y-yb-yb)^2+(z-zb)^2)^0.5)...
           +log(x-xb-xb+((x-xb-xb)^2+(y-yb+yb)^2+(z-zb)^2)^0.5)...
           -log(x-xb+xb+((x-xb+xb)^2+(y-yb+yb)^2+(z-zb)^2)^0.5)...
           +log(x-xb-xb+((x-xb-xb)^2+(y-yb-yb)^2+(z+zb)^2)^0.5)...
           -log(x-xb+xb+((x-xb+xb)^2+(y-yb-yb)^2+(z+zb)^2)^0.5)...
           -log(x-xb-xb+((x-xb-xb)^2+(y-yb+yb)^2+(z+zb)^2)^0.5)...
           +log(x-xb+xb+((x-xb+xb)^2+(y-yb+yb)^2+(z+zb)^2)^0.5))...
           -((mu0*M0)/(4*pi))*(-log(x-xb-xb+((x-xb-xb)^2+(y+yb-yb)^2+(z-zb)^2)^0.5)...
           +log(x-xb+xb+((x-xb+xb)^2+(y+yb-yb)^2+(z-zb)^2)^0.5)...
           +log(x-xb-xb+((x-xb-xb)^2+(y+yb+yb)^2+(z-zb)^2)^0.5)...
           -log(x-xb+xb+((x-xb+xb)^2+(y+yb+yb)^2+(z-zb)^2)^0.5)...
           +log(x-xb-xb+((x-xb-xb)^2+(y+yb-yb)^2+(z+zb)^2)^0.5)...
           -log(x-xb+xb+((x-xb+xb)^2+(y+yb-yb)^2+(z+zb)^2)^0.5)...
           -log(x-xb-xb+((x-xb-xb)^2+(y+yb+yb)^2+(z+zb)^2)^0.5)...
           +log(x-xb+xb+((x-xb+xb)^2+(y+yb+yb)^2+(z+zb)^2)^0.5));
       
       Bz=-((mu0*M0)/(4*pi))*(-(((x+xb-xb)*(z-zb))/(abs(x+xb-xb)*abs(z-zb)))...
           *atan((abs(x+xb-xb)*(y+yb-yb))/(abs(z-zb)*((x+xb-xb)^2+(y+yb-yb)^2+(z-zb)^2)^0.5))...
           +(((x+xb+xb)*(z-zb))/(abs(x+xb+xb)*abs(z-zb)))...
           *atan((abs(x+xb+xb)*(y+yb-yb))/(abs(z-zb)*((x+xb+xb)^2+(y+yb-yb)^2+(z-zb)^2)^0.5))...
           +(((x+xb-xb)*(z-zb))/(abs(x+xb-xb)*abs(z-zb)))...
           *atan((abs(x+xb-xb)*(y+yb+yb))/(abs(z-zb)*((x+xb-xb)^2+(y+yb+yb)^2+(z-zb)^2)^0.5))...
           -(((x+xb+xb)*(z-zb))/(abs(x+xb+xb)*abs(z-zb)))...
           *atan((abs(x+xb+xb)*(y+yb+yb))/(abs(z-zb)*((x+xb+xb)^2+(y+yb+yb)^2+(z-zb)^2)^0.5))...
           +(((x+xb-xb)*(z+zb))/(abs(x+xb-xb)*abs(z+zb)))...
           *atan((abs(x+xb-xb)*(y+yb-yb))/(abs(z+zb)*((x+xb-xb)^2+(y+yb-yb)^2+(z+zb)^2)^0.5))...
           -(((x+xb+xb)*(z+zb))/(abs(x+xb+xb)*abs(z+zb)))...
           *atan((abs(x+xb+xb)*(y+yb-yb))/(abs(z+zb)*((x+xb+xb)^2+(y+yb-yb)^2+(z+zb)^2)^0.5))...
           -(((x+xb-xb)*(z+zb))/(abs(x+xb-xb)*abs(z+zb)))...
           *atan((abs(x+xb-xb)*(y+yb+yb))/(abs(z+zb)*((x+xb-xb)^2+(y+yb+yb)^2+(z+zb)^2)^0.5))...
           +(((x+xb+xb)*(z+zb))/(abs(x+xb+xb)*abs(z+zb)))...
           *atan((abs(x+xb+xb)*(y+yb+yb))/(abs(z+zb)*((x+xb+xb)^2+(y+yb+yb)^2+(z+zb)^2)^0.5)))...
           +((mu0*M0)/(4*pi))*(-(((x+xb-xb)*(z-zb))/(abs(x+xb-xb)*abs(z-zb)))...
           *atan((abs(x+xb-xb)*(y-yb-yb))/(abs(z-zb)*((x+xb-xb)^2+(y-yb-yb)^2+(z-zb)^2)^0.5))...
           +(((x+xb+xb)*(z-zb))/(abs(x+xb+xb)*abs(z-zb)))...
           *atan((abs(x+xb+xb)*(y-yb-yb))/(abs(z-zb)*((x+xb+xb)^2+(y-yb-yb)^2+(z-zb)^2)^0.5))...
           +(((x+xb-xb)*(z-zb))/(abs(x+xb-xb)*abs(z-zb)))...
           *atan((abs(x+xb-xb)*(y-yb+yb))/(abs(z-zb)*((x+xb-xb)^2+(y-yb+yb)^2+(z-zb)^2)^0.5))...
           -(((x+xb+xb)*(z-zb))/(abs(x+xb+xb)*abs(z-zb)))...
           *atan((abs(x+xb+xb)*(y-yb+yb))/(abs(z-zb)*((x+xb+xb)^2+(y-yb+yb)^2+(z-zb)^2)^0.5))...
           +(((x+xb-xb)*(z+zb))/(abs(x+xb-xb)*abs(z+zb)))...
           *atan((abs(x+xb-xb)*(y-yb-yb))/(abs(z+zb)*((x+xb-xb)^2+(y-yb-yb)^2+(z+zb)^2)^0.5))...
           -(((x+xb+xb)*(z+zb))/(abs(x+xb+xb)*abs(z+zb)))...
           *atan((abs(x+xb+xb)*(y-yb-yb))/(abs(z+zb)*((x+xb+xb)^2+(y-yb-yb)^2+(z+zb)^2)^0.5))...
           -(((x+xb-xb)*(z+zb))/(abs(x+xb-xb)*abs(z+zb)))...
           *atan((abs(x+xb-xb)*(y-yb+yb))/(abs(z+zb)*((x+xb-xb)^2+(y-yb+yb)^2+(z+zb)^2)^0.5))...
           +(((x+xb+xb)*(z+zb))/(abs(x+xb+xb)*abs(z+zb)))...
           *atan((abs(x+xb+xb)*(y-yb+yb))/(abs(z+zb)*((x+xb+xb)^2+(y-yb+yb)^2+(z+zb)^2)^0.5)))...
           -((mu0*M0)/(4*pi))*(-(((x-xb-xb)*(z-zb))/(abs(x-xb-xb)*abs(z-zb)))...
           *atan((abs(x-xb-xb)*(y-yb-yb))/(abs(z-zb)*((x-xb-xb)^2+(y-yb-yb)^2+(z-zb)^2)^0.5))...
           +(((x-xb+xb)*(z-zb))/(abs(x-xb+xb)*abs(z-zb)))...
           *atan((abs(x-xb+xb)*(y-yb-yb))/(abs(z-zb)*((x-xb+xb)^2+(y-yb-yb)^2+(z-zb)^2)^0.5))...
           +(((x-xb-xb)*(z-zb))/(abs(x-xb-xb)*abs(z-zb)))...
           *atan((abs(x-xb-xb)*(y-yb+yb))/(abs(z-zb)*((x-xb-xb)^2+(y-yb+yb)^2+(z-zb)^2)^0.5))...
           -(((x-xb+xb)*(z-zb))/(abs(x-xb+xb)*abs(z-zb)))...
           *atan((abs(x-xb+xb)*(y-yb+yb))/(abs(z-zb)*((x-xb+xb)^2+(y-yb+yb)^2+(z-zb)^2)^0.5))...
           +(((x-xb-xb)*(z+zb))/(abs(x-xb-xb)*abs(z+zb)))...
           *atan((abs(x-xb-xb)*(y-yb-yb))/(abs(z+zb)*((x-xb-xb)^2+(y-yb-yb)^2+(z+zb)^2)^0.5))...
           -(((x-xb+xb)*(z+zb))/(abs(x-xb+xb)*abs(z+zb)))...
           *atan((abs(x-xb+xb)*(y-yb-yb))/(abs(z+zb)*((x-xb+xb)^2+(y-yb-yb)^2+(z+zb)^2)^0.5))...
           -(((x-xb-xb)*(z+zb))/(abs(x-xb-xb)*abs(z+zb)))...
           *atan((abs(x-xb-xb)*(y-yb+yb))/(abs(z+zb)*((x-xb-xb)^2+(y-yb+yb)^2+(z+zb)^2)^0.5))...
           +(((x-xb+xb)*(z+zb))/(abs(x-xb+xb)*abs(z+zb)))...
           *atan((abs(x-xb+xb)*(y-yb+yb))/(abs(z+zb)*((x-xb+xb)^2+(y-yb+yb)^2+(z+zb)^2)^0.5)))...
           +((mu0*M0)/(4*pi))*(-(((x-xb-xb)*(z-zb))/(abs(x-xb-xb)*abs(z-zb)))...
           *atan((abs(x-xb-xb)*(y+yb-yb))/(abs(z-zb)*((x-xb-xb)^2+(y+yb-yb)^2+(z-zb)^2)^0.5))...
           +(((x-xb+xb)*(z-zb))/(abs(x-xb+xb)*abs(z-zb)))...
           *atan((abs(x-xb+xb)*(y+yb-yb))/(abs(z-zb)*((x-xb+xb)^2+(y+yb-yb)^2+(z-zb)^2)^0.5))...
           +(((x-xb-xb)*(z-zb))/(abs(x-xb-xb)*abs(z-zb)))...
           *atan((abs(x-xb-xb)*(y+yb+yb))/(abs(z-zb)*((x-xb-xb)^2+(y+yb+yb)^2+(z-zb)^2)^0.5))...
           -(((x-xb+xb)*(z-zb))/(abs(x-xb+xb)*abs(z-zb)))...
           *atan((abs(x-xb+xb)*(y+yb+yb))/(abs(z-zb)*((x-xb+xb)^2+(y+yb+yb)^2+(z-zb)^2)^0.5))...
           +(((x-xb-xb)*(z+zb))/(abs(x-xb-xb)*abs(z+zb)))...
           *atan((abs(x-xb-xb)*(y+yb-yb))/(abs(z+zb)*((x-xb-xb)^2+(y+yb-yb)^2+(z+zb)^2)^0.5))...
           -(((x-xb+xb)*(z+zb))/(abs(x-xb+xb)*abs(z+zb)))...
           *atan((abs(x-xb+xb)*(y+yb-yb))/(abs(z+zb)*((x-xb+xb)^2+(y+yb-yb)^2+(z+zb)^2)^0.5))...
           -(((x-xb-xb)*(z+zb))/(abs(x-xb-xb)*abs(z+zb)))...
           *atan((abs(x-xb-xb)*(y+yb+yb))/(abs(z+zb)*((x-xb-xb)^2+(y+yb+yb)^2+(z+zb)^2)^0.5))...
           +(((x-xb+xb)*(z+zb))/(abs(x-xb+xb)*abs(z+zb)))...
           *atan((abs(x-xb+xb)*(y+yb+yb))/(abs(z+zb)*((x-xb+xb)^2+(y+yb+yb)^2+(z+zb)^2)^0.5)));
        
        %Determination of grad of the magnetic field
        Bxx=Bx*diff(Bx,x)+By*diff(Bx,y)+Bz*diff(Bx,z); 
        Byy=Bx*diff(By,x)+By*diff(By,y)+Bz*diff(By,z);
        Bzz=Bx*diff(Bz,x)+By*diff(Bz,y)+Bz*diff(Bz,z);
        
        save('field.mat');

